chain_width                = 40
match_block_trailing_comma = true
merge_derives              = false
style_edition              = "2024"
use_field_init_shorthand   = true
use_small_heuristics       = "Max"
