apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "inari.fullname" . }}
  labels:
    {{- include "inari.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      {{- include "inari.selectorLabels" . | nindent 6 }}
