"""Trusted Device Capability authority for Device Work admission."""

from .authority import (
    AdmissionAuthorizer,
    canonical_digest,
    canonical_json_bytes,
    DeviceCapabilityAuthority,
    PreIoCapabilityChecker,
    PreIoCapabilityGate,
)
from .models import (
    AdmissionPermit,
    AuthorityRevision,
    AuthorityScope,
    AuthorityProof,
    AuthorityState,
    AuthorityStatus,
    BindingRevision,
    CapabilityAdmissionTarget,
    CapabilityStreamTarget,
    DeviceCapability,
    DeviceObservation,
    DeviceTestEvidence,
    DeviceTestResult,
    DriverProfile,
    HardwareCertificationMatrixRow,
    OutputEvidence,
    RevocationSubjectKind,
    ScopeKind,
    SignedDeviceObservation,
    SignedDeviceTestEvidence,
    SignedBindingRevision,
    SignedAuthorityRevision,
    SignedDriverProfile,
    SignedHardwareCertificationMatrixRow,
    SignerPurpose,
    SignerRecord,
    SignerState,
)
from .ports import AuthorityProjectionReader, DeviceObservationReader
from .sqlite import SqliteDeviceAuthorityReader
from .errors import AuthorityError, AuthorityErrorCode

__all__ = [
    "AdmissionAuthorizer",
    "AdmissionPermit",
    "AuthorityError",
    "AuthorityErrorCode",
    "AuthorityProjectionReader",
    "AuthorityRevision",
    "AuthorityScope",
    "AuthorityProof",
    "AuthorityState",
    "AuthorityStatus",
    "BindingRevision",
    "CapabilityAdmissionTarget",
    "CapabilityStreamTarget",
    "canonical_digest",
    "canonical_json_bytes",
    "DeviceCapability",
    "DeviceCapabilityAuthority",
    "DeviceObservation",
    "DeviceObservationReader",
    "DeviceTestEvidence",
    "DeviceTestResult",
    "DriverProfile",
    "HardwareCertificationMatrixRow",
    "OutputEvidence",
    "RevocationSubjectKind",
    "PreIoCapabilityChecker",
    "PreIoCapabilityGate",
    "ScopeKind",
    "SignedDeviceObservation",
    "SignedDeviceTestEvidence",
    "SignedBindingRevision",
    "SignedAuthorityRevision",
    "SignedDriverProfile",
    "SignedHardwareCertificationMatrixRow",
    "SignerPurpose",
    "SqliteDeviceAuthorityReader",
    "SignerRecord",
    "SignerState",
]
